### ISSUE TITLE
got error code FAB9A2C5 from tableau when using live data source

### ISSUE THREAD

**Issue by yehudaf1** [ClickHouse/clickhouse-tableau-connector-jdbc#72] opened 2024-04-03 13:02 UTC
Hi 

we are using clickhouse JDBC connecter to connect from tableau to clickhouse.
In tableau we use it as publish data source.  

Unable to complete action
The connection to the data source might have been lost.
Error Code: FAB9A2C5
Error executing subquery id: "1151"
An error occurred while communicating with data source 'DATASOTCENAME' 
Code: 47. DB::Exception: Unknown identifier '__measure__0' in aggregate function 'min(__measure__0) AS `$temp3_output`'. (UNKNOWN_IDENTIFIER) (version 23.10.5.20 (official build))
, server ClickHouseNode [uri=http://clickhouse:8123/default, options={custom_http_params=join_use_nulls=1,session_id=tableau-jdbc-connector-1712144566986-27492351,typeMappings=UInt64=java.lang.String,UInt128=java.lang.String,Int128=java.lang.String,UInt256=java.lang.String,Int256=java.lang.String,socket_timeout=300000}]@270777070
DataServiceFailure

**Comment by mshustov** [comment] 2024-04-19 14:55
duplicate of https://github.com/ClickHouse/clickhouse-tableau-connector-jdbc/issues/67

**Closed by mshustov** 2024-04-19 14:55 UTC
